from _typeshed import Incomplete
from cpipe.module.cinferencer import CClassifier as CClassifier, CEmbedding as CEmbedding
from cpipe.module.dataprocessing import load_data as load_data
from cpipe.module.node import Node as Node

def dino_preprocessor(self, raw_bgr_image, num) -> None:
    """
    Preprocess the raw image for classification
    Args:
        self: ProcessThread object
        raw_bgr_image: input image
        num: image index

    Returns: None

    """

class DinoEmbedding(CEmbedding):
    preprocessor: Incomplete
    embeddings: Incomplete
    need_embedding: Incomplete
    softmax_temperature: Incomplete
    cos: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize=(3, 224, 224), class_names=(), max_batch_size: int = 1, conf_thres: float = 0.0, embeddings=None, need_embedding: bool = False, softmax_temperature=None, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, *args, **kwargs) -> None:
        '''
        Adaface is a class for Adaface.
        Args:
            nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The queue size.
            inputSize: (list) The input size. e.g. [3, 112, 112]
            class_names: (list) The class names.
            max_batch_size: (int) The max batch size.
            conf_thres: (float) The confidence threshold.
            warmup: (bool) The warmup flag.
            device: (str) The device. e.g. "cuda:0" or "cpu"
            threading_num: (int) The threading number.
            area_flag: (bool) The area flag.
            secondary_class_names: (list) The secondary class names.
            input_names: (list) The input_names.
            output_names: (list) The output_names.
            embeddings: (list) The embeddings.
            gray_mode: (bool) The gray mode flag.
        '''
    def before_start(self) -> None:
        """
        The function to be executed before the start of the model.
        Returns: None

        """
    def matching(self, embeddings, face_library):
        """
        Matching function.
        Args:
            embeddings: The embeddings.
            face_library: The face library.

        Returns: The matching result.

        """
    def preprocess(self, inputs, *args, **kwargs): ...
    def infer(self, inputs, *args, **kwargs):
        """
        Model inference method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: model output data

        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """

class DinoClassifier(CClassifier):
    preprocessor: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names, max_batch_size: int = 1, conf_thres: float = 0.25, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, *args, **kwargs) -> None:
        '''
        DinoClassifier is a class for Dino.
        Args:
            nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The queue size.
            inputSize: (list) The input size. e.g. [3, 224, 224]
            class_names: (list) The class names.
            max_batch_size: (int) The max batch size.
            conf_thres: (float) The confidence threshold.
            warmup: (bool) The warmup flag.
            device: (str) The device. e.g. "cuda:0" or "cpu"
            threading_num: (int) The threading number.
            area_flag: (bool) The area flag.
            secondary_class_names: (list) The secondary class names.
            input_names: (list) The input_names.
            output_names: (list) The output_names.
            gray_mode: (bool) Whether to use gray mode.
        '''
    def infer(self, inputs, *args, **kwargs):
        """
        The infer function of the model
        Args:
            inputs: inputs[0]: batch_imgs, inputs[1]: original image, inputs[2]: batch_size
            *args:
            **kwargs:

        Returns: The result of the model.

        """
