from _typeshed import Incomplete
from cpipe.module.cdata import Box as Box
from cpipe.module.cinferencer import CDetector as CDetector
from cpipe.module.dataprocessing import letterbox as letterbox, load_data as load_data, non_max_suppression as non_max_suppression, process_mask_native as process_mask_native, scale_boxes as scale_boxes

def preprocess_fastsam(self, raw_bgr_image, num) -> None:
    """
    Preprocess the raw image for YOLOv7.
    Args:
        self: ProcessThread object
        raw_bgr_image: input image
        num: image index

    Returns: None

    """

class FastSAM(CDetector):
    preprocessor: Incomplete
    need_mask: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names=('object',), valid_class_names=None, max_batch_size: int = 1, conf_thres: float = 0.25, iou_thres: float = 0.45, need_mask: bool = False, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, save_top_n_objects=None, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=['output0', 'output1', 'onnx::Reshape_1301', 'onnx::Reshape_1320', 'onnx::Concat_1263', 'onnx::Shape_1215'], gray_mode: bool = False, *args, **kwargs) -> None:
        """
        FastSAM is a segmentation model.

        Args:
            nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The queue size.
            inputSize: (list) The input size. e.g. [3, 416, 416]
            class_names: (list) The class names.
            valid_class_names: (list) The valid class names.
            max_batch_size: (int) The max batch size.
            conf_thres: (float) The confidence threshold.
            iou_thres: (float) The iou threshold.
            warmup: (bool) The warmup flag.
            device: (str) The device.
            threading_num: (int) The threading number.
            save_top_n_objects: (int) The save top n objects.
            area_flag: (bool) The area flag.
            secondary_class_names: (list) The secondary class names.
            input_names: (list) The input names.
            output_names: (list) The output names.
            gray_mode: (bool) Whether to use gray mode.

        Returns: None

        """
    def preprocess(self, inputs, *args, **kwargs): ...
    def infer(self, inputs, *args, **kwargs):
        """
        Model inference method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: model output data

        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def postprocess(self, inputs, *args, **kwargs):
        """Applies non-max suppression and processes detections for each image in an input batch."""
