import asyncio
from _typeshed import Incomplete

class CEvent(asyncio.Event):
    data: Incomplete
    def __init__(self) -> None: ...

class CEventQueue:
    input_queue: Incomplete
    output_queue: Incomplete
    def __init__(self, queue_size: int = 10) -> None: ...
    def send(self, data): ...
    def get(self): ...
    def response(self, data) -> None: ...
