from _typeshed import Incomplete
from cpipe.module.cdata import Box as Box, Classification as Classification, Person as Person
from cpipe.module.cmodel import Cmodel as Cmodel
from cpipe.module.dataprocessing import load_data as load_data, preprocess_yolov7 as preprocess_yolov7
from cpipe.module.inferenceengine import InferenceEngine as InferenceEngine
from cpipe.module.node import Node as Node

class CEmbedding(InferenceEngine):
    conf_threshold: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names=(), max_batch_size: int = 1, conf_thres: float = 0.0, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, *args, **kwargs) -> None:
        """
        CEmbedding is a class for Embedding model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            max_batch_size: (int) The maximum batch size.
            conf_thres: (float) The confidence threshold. Default is 0.0.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            gray_mode: (bool) Whether to use gray mode.
        """
    def infer(self, inputs, *args, **kwargs):
        """
        Model inference method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: model output data

        """

class CFace(InferenceEngine):
    save_face_image: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names=(), max_batch_size: int = 1, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, save_face_image: bool = True, gray_mode: bool = False, *args, **kwargs) -> None:
        """
        CFace is a class for Face model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            max_batch_size: (int) The maximum batch size.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            save_face_image: (bool) Whether to save the face image for cdata output.
            gray_mode: (bool) Whether to use gray mode.
        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def _start_secondary(self) -> None:
        """
        The entry function for the current node (process) to run in two-stage mode, all the logic processing of the current node is completed here.
        Returns: None

        """

class CClassifier(InferenceEngine):
    conf_thres: Incomplete
    need_softmax: Incomplete
    label_id_name: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names=(), max_batch_size: int = 1, conf_thres: float = 0.25, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, need_softmax: bool = True, *args, **kwargs) -> None:
        """
        CClassifier is a class for Classifier model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            max_batch_size: (int) The maximum batch size.
            conf_thres: (float) The confidence threshold.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            gray_mode: (bool) Whether to use gray mode.
            need_softmax: (bool) Whether to use softmax for post-processing. Default is True.
        """
    def preprocess(self, frames, *args, **kwargs):
        """
        Model input data preprocessing method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: input data

        """
    def infer(self, inputs, *args, **kwargs):
        """
        Model inference method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: model output data

        """
    def postprocess(self, inputs, *args, **kwargs):
        """
        Model output data post-processing method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: output data

        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """

class CDetector(InferenceEngine):
    valid_class_idx: Incomplete
    save_top_n_objects: Incomplete
    conf_threshold: Incomplete
    iou_threshold: Incomplete
    preprocessor: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names, valid_class_names=None, max_batch_size: int = 1, conf_thres: float = 0.25, iou_thres: float = 0.45, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, save_top_n_objects=None, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, *args, **kwargs) -> None:
        """
        CDetector is a class for Detector model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            valid_class_names: (list) The valid class names.
            max_batch_size: (int) The maximum batch size.
            conf_thres: (float) The confidence threshold.
            iou_thres: (float) The iou threshold.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            save_top_n_objects: (int) The number of objects to save.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            gray_mode: (bool) Whether to use gray mode.
        """
    def preprocess(self, inputs, *args, **kwargs):
        """
        Model input data preprocessing method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: input data

        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """
    def before_start(self) -> None:
        """
        This method can be used to customize the initialization operation of the current node, which will be executed before the node is ready.
        Returns: None

        """

class COBBDetector(CDetector):
    pass_class_idx: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names, valid_class_names=None, max_batch_size: int = 1, conf_thres: float = 0.25, iou_thres: float = 0.45, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, save_top_n_objects=None, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, *args, **kwargs) -> None:
        """
        COBBDetector is a class for Object Detection model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            valid_class_names: (list) The valid class names.
            max_batch_size: (int) The maximum batch size.
            conf_thres: (float) The confidence threshold.
            iou_thres: (float) The iou threshold.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            save_top_n_objects: (int) The number of objects to save.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            gray_mode: (bool) Whether to use gray mode.
        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """

class CSemanticSegmentation(InferenceEngine):
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names, max_batch_size: int = 1, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, *args, **kwargs) -> None:
        """
        CSemanticSegmentation is a class for Semantic Segmentation model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            max_batch_size: (int) The maximum batch size.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            gray_mode: (bool) Whether to use gray mode.
        """
    def infer(self, inputs, *args, **kwargs):
        """
        Model inference method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: model output data

        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """

class CInstanceSegmentation(InferenceEngine):
    valid_class_idx: Incomplete
    save_top_n_objects: Incomplete
    conf_threshold: Incomplete
    iou_threshold: Incomplete
    return_mask: Incomplete
    def __init__(self, nodeName, modelPath, queue_size, inputSize, class_names, valid_class_names=None, max_batch_size: int = 1, conf_thres: float = 0.25, iou_thres: float = 0.45, warmup: bool = True, device: str = 'cuda:0', threading_num: int = 4, save_top_n_objects=None, area_flag: bool = False, secondary_class_names=None, input_names=None, output_names=None, gray_mode: bool = False, return_masks: bool = False, *args, **kwargs) -> None:
        """
        CDetector is a class for Detector model.
        Args:
            nodeName: nodeName: (str) The name of the node.
            modelPath: (str) The path of the model.
            queue_size: (int) The size of the queue.
            inputSize: (list) The size of the input image.
            class_names: (list) The class names.
            valid_class_names: (list) The valid class names.
            max_batch_size: (int) The maximum batch size.
            conf_thres: (float) The confidence threshold.
            iou_thres: (float) The iou threshold.
            warmup: (bool) Whether to warm up the model.
            device: (str) The device of the model, CPU(cpu) or GPU(cuda:x).
            threading_num: (int) The number of preprocessing threads.
            save_top_n_objects: (int) The number of objects to save.
            area_flag: (bool) Whether to use the area mask.
            input_names: (list) The input names of the model.
            output_names: (list) The output names of the model.
            secondary_class_names: (list) The class names of the previous node that need to be processed in the two-stage mode.
            gray_mode: (bool) Whether to use gray mode.
            return_masks: (bool) Whether to return masks.
        """
    def preprocess(self, inputs, *args, **kwargs):
        """
        Model input data preprocessing method.
        Args:
            inputs: input data
            *args:
            **kwargs:

        Returns: input data

        """
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the one-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None:
        """
        The result processing function of the model inference (or logic) of the current node in the two-stage mode is completed,
         and the result is processed and saved to the CData object.
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            streamer_names: The stream name corresponding to each batch.
            box_idxes: The index of the Box in boxes corresponding to each batch.
            boxes: A list of all Box objects.
        Returns: None

        """
    def before_start(self) -> None:
        """
        This method can be used to customize the initialization operation of the current node, which will be executed before the node is ready.
        Returns: None

        """
