def iou_batch(bboxes1, bboxes2):
    """
    From SORT: Computes IOU between two bboxes in the form [x1,y1,x2,y2]
    """
def speed_direction_batch(dets, tracks): ...
def linear_assignment(cost_matrix): ...
def associate(detections, trackers, iou_threshold, velocities, previous_obs, vdc_weight): ...
