from _typeshed import Incomplete
from cpipe.module.inferenceengine import InferenceEngine as InferenceEngine
from cpipe.module.model.tracker.deepsort_tracker import DeepSORTTracker as DeepSORTTracker
from cpipe.module.model.tracker.ocsort_tracker import OCSORTTracker as OCSORTTracker
from cpipe.module.node import Node as Node

class Tracker(InferenceEngine):
    tracker_dict: Incomplete
    nodeName: Incomplete
    queue_size: Incomplete
    tracker_type: Incomplete
    scale_ratio: Incomplete
    judge_reid: bool
    dump_images: Incomplete
    is_person_embedding: Incomplete
    cfg_dict: Incomplete
    tracker_kernel: Incomplete
    def __init__(self, nodeName, queue_size, config_tracker=None, tacker_type: str = 'ocsort', scale_ratio: float = 1.0, secondary_class_names=None, dump_images: bool = True, is_person_embedding: bool = True) -> None:
        '''
        Args:
            nodeName: (str) The name of the node
            queue_size: (int) The size of the queue
            config_tracker: (dict) The configuration of the tracker
                "ocsort": {
                    \'det_thresh\': 0.4, # 目标检测阈值
                    \'max_age\': 5, # 超过5帧没有检测到目标，将目标删除
                    \'min_hits\': 3, # 目标出现3帧后才开始跟踪
                    \'iou_threshold\': 0.3, # iou阈值
                    \'delta_t\': 3, # 时间间隔
                }
                "deepsort_reid": {
                    \'input_size\': [64, 192], # 输入尺寸
                    \'min_box_area\': 0,
                    \'vertical_ratio\': -1,
                    \'budget\': 100,
                    \'max_age\': 70,
                    \'n_init\': 3,
                    \'metric_type\': \'cosine\',
                    \'matching_threshold\': 0.2,
                    \'max_iou_distance\': 0.9,
                    \'motion\': \'KalmanFilter\'
                }
            tacker_type: (str) The type of the tracker, "ocsort" or "deepsort_reid"
            scale_ratio: (float) The scale ratio of the input image
            secondary_class_names: (list) The secondary class names
            dump_images: (bool) Whether to dump images
            is_person_embedding: (bool) Whether to use person embedding
        '''
    def to_cdata(self, pred, new_cdata, frames, streamer_names, *args, **kwargs) -> None:
        """
        Args:
            pred: model output.
            new_cdata: The CData object generated by the current node.
            frames: The original image of each batch corresponding to the inference.
            streamer_names: The stream name corresponding to each batch.
        Returns: None

        """
    def before_start(self) -> None: ...
    def _start(self) -> None: ...
    def to_cdata_secondary(self, pred, new_cdata, streamer_names, box_idxes, boxes, *args, **kwargs) -> None: ...
